# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 14:45
# Modified for PostgreSQL compatibility
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20180131_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='md5sum',
            field=models.CharField(max_length=32),
        ),
    ]
