# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20180211_0027'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE `frontend_post` ADD COLUMN `md5sum2` BINARY(16) DEFAULT 0 NOT NULL;"
                          "UPDATE `frontend_post` set `md5sum2` = unhex(`md5sum`);"
                          "ALTER TABLE frontend_post DROP COLUMN md5sum;"
                          "ALTER TABLE frontend_post CHANGE COLUMN md5sum2 md5sum BINARY(16) NOT NULL;"
                          "CREATE INDEX md5sum_index USING HASH ON frontend_post (feed_id, md5sum);",
                          state_operations=[
                              migrations.AlterField(
                                  model_name='post',
                                  name='md5sum',
                                  field=models.BinaryField(),
                              ),
                          ]),
    ]
